package constants

// config init params.
const (
	ConfigIDKey               = "id"
	ConfigRegionKey           = "region"
	ConfigAccessKeyID         = "accessKeyId"
	ConfigSecretKey           = "secretKey"
	ConfigAppKey              = "app"
	ConfigEnvKey              = "env"
	ConfigTypeKey             = "configType"
	ConfigNamesKey            = "configNames"
	ConfigDirectoryKey        = "configsDirectory"
	ConfigSecretsDirectoryKey = "secretsDirectory"
	ConfigCredentialsModeKey  = "credentialsMode"
)

// config names.
const (
	LoggerConfig      = "logger"
	ApplicationConfig = "application"
	DatabaseConfig    = "database"
	JWTConfig         = "jwt"
	APIConfig         = "api"
	S2SAuthConfig     = "s2sauth"
)

// config constants.
const (
	LogLevelConfigKey                                                         = "level"
	LogParamsConfigKey                                                        = "params"
	ApplicationMetricsLinearBucketStartConfigKey                              = "metrics.linearBucket.start"
	ApplicationMetricsLinearBucketWidthConfigKey                              = "metrics.linearBucket.width"
	ApplicationMetricsLinearBucketCountConfigKey                              = "metrics.linearBucket.count"
	DatabaseDriverNameConfigKey                                               = "rds.driverName"
	DatabaseURLConfigKey                                                      = "rds.url"
	DatabaseMaxOpenConnectionsConfigKey                                       = "rds.maxOpenConnections"
	DatabaseMaxIdleConnectionsConfigKey                                       = "rds.maxIdleConnections"
	DatabaseConnectionMaxLifetimeInSecondsConfigKey                           = "rds.connectionMaxLifetimeInSeconds"
	DatabaseConnectionMaxIdleTimeInSecondsConfigKey                           = "rds.connectionMaxIdleTimeInSeconds"
	APIConditionalOrdersCreateScreenerConfigKey                               = "conditionalOrdersCreateScreener"
	APIConditionalOrdersCreateScreenerURLConfigKey                            = "conditionalOrdersCreateScreener.url"
	APIConditionalOrdersCreateScreenerHeadersConfigKey                        = "conditionalOrdersCreateScreener.headers"
	APIConditionalOrdersCreateBacktestConfigKey                               = "conditionalOrdersCreateBacktest"
	APIConditionalOrdersCreateBacktestURLConfigKey                            = "conditionalOrdersCreateBacktest.url"
	APIConditionalOrdersCreateBacktestHeadersConfigKey                        = "conditionalOrdersCreateBacktest.headers"
	APIConditionalOrderGetBacktestSummaryConfigKey                            = "conditionalOrdersGetBacktestSummary"
	APIConditionalOrderGetBacktestSummaryURLConfigKey                         = "conditionalOrdersGetBacktestSummary.url"
	APIConditionalOrderGetBacktestSummaryHeadersLConfigKey                    = "conditionalOrdersGetBacktestSummary.headers"
	S2SAuthSupportedServicesConfigKey                                         = "supportedServices"
	S2SAuthKeyIDConfigKey                                                     = "keyId"
	S2SAuthPrivateKeyConfigKey                                                = "privateKey"
	S2SAuthTargetApplicationNamesConfigKey                                    = "targetApplicationNames"
	S2SAuthExpiryInSecondsConfigKey                                           = "expiryInSeconds"
	S2SAuthIssuerConfigKey                                                    = "issuer"
	S2SAuthSubjectConfigKey                                                   = "subject"
	APIScripAndHolidayMasterAccessTokenConfigKey                              = "scripAndHolidayMasterAccessToken"
	APIScripAndHolidayMasterAccessTokenURLConfigKey                           = "scripAndHolidayMasterAccessToken.url"
	APIScripAndHolidayMasterAccessTokenHeadersConfigKey                       = "scripAndHolidayMasterAccessToken.headers"
	APIScripMasterSecInfoConfigKey                                            = "scripMasterSecInfo"
	APIScripMasterSecInfoURLConfigKey                                         = "scripMasterSecInfo.url"
	APIScripMasterSecInfoHeadersConfigKey                                     = "scripMasterSecInfo.headers"
	ApplicationScripMasterPollFrequencyInMinutesConfigKey                     = "scripMaster.pollFrequencyInMinutes"
	ApplicationScripMasterS2sAuthServiceNameConfigKey                         = "scripMaster.s2sAuthServiceName"
	ApplicationExchangeSegmentsConfigKey                                      = "exchangeSegments"
	ApplicationTokenTypesConfigKey                                            = "tokenTypes"
	APIServiceConfigKey                                                       = "service"
	ApplicationBacktestDurationInDaysConfigKey                                = "backtestDurationInDays"
	APINSESecurityArchivesForDeliveriesAndTradesConfigKey                     = "nseSecurityArchivesForDeliveriesAndTrades"
	APINSESecurityArchivesForDeliveriesAndTradesURLConfigKey                  = "nseSecurityArchivesForDeliveriesAndTrades.url"
	APINSESecurityArchivesForDeliveriesAndTradesHeadersConfigKey              = "nseSecurityArchivesForDeliveriesAndTrades.headers"
	APINifty50Top10HoldingsConfigKey                                          = "nifty50Top10Holdings"
	APINifty50Top10HoldingsURLConfigKey                                       = "nifty50Top10Holdings.url"
	APINifty50Top10HoldingsHeadersConfigKey                                   = "nifty50Top10Holdings.headers"
	APINSEHistoricDataConfigKey                                               = "nseHistoricData"
	APINSEHistoricDataURLConfigKey                                            = "nseHistoricData.url"
	APINSEHistoricDataHeadersConfigKey                                        = "nseHistoricData.headers"
	ApplicationJobsNSESecurityArchivesForDeliveriesAndTradesAtConfigKey       = "jobs.nseSecurityArchivesForDeliveriesAndTrades.at"
	ApplicationJobsNSESecurityArchivesForDeliveriesAndTradesDataTypeConfigKey = "jobs.nseSecurityArchivesForDeliveriesAndTrades.dataType"
	ApplicationJobsNSESecurityArchivesForDeliveriesAndTradesSeriesConfigKey   = "jobs.nseSecurityArchivesForDeliveriesAndTrades.series"
	ApplicationScreenerNonIntraDayExecutionAtConfigKey                        = "screenerNonIntraDayExecution.at"
	ApplicationScreenerNonIntraDayExecutionOffsetInMinutesConfigKey           = "screenerNonIntraDayExecution.offsetInMinutes"
	ApplicationJobsNifty50Top10HoldingsAtConfigKey                            = "jobs.nifty50Top10Holdings.at"
	ApplicationJobsNifty50Top10HoldingsExchangeConfigKey                      = "jobs.nifty50Top10Holdings.exchange"
	ApplicationJobsNifty50Top10HoldingsTokenTypeConfigKey                     = "jobs.nifty50Top10Holdings.tokenType"
	ApplicationJobsNSEHistoricDataExchangeConfigKey                           = "jobs.nseHistoricData.exchange"
	ApplicationJobsNSEHistoricDataTokenTypeConfigKey                          = "jobs.nseHistoricData.tokenType"
	S2SAuthPublicKeysConfigKey                                                = "publicKeys"
	ApplicationJobsStrategyBacktestSummaryFrequencyInSecondsConfigKey         = "jobs.strategyBacktestSummary.frequencyInSeconds"
	ApplicationJobsStrategyBacktestSummaryLimitConfigKey                      = "jobs.strategyBacktestSummary.limit"
	ApplicationJobsSebiPublicReportsAtConfigKey                               = "jobs.sebiPublicReports.at"

	ApplicationAWSLabsEndpointConfigKey = "awsconfigs.aws_labs_endpoint"

	ApplicationOpensearchStockSearchRecommendIndexConfigKey = "opensearch.stock_search_recommend_index"
	ApplicationOpensearchStockSearchMomentumIndexConfigKey  = "opensearch.stock_sentiment_momentum_index"
	ApplicationOpensearchStockSearchAboutUsIndexConfigKey   = "opensearch.stock_search_about_us_index"
	ApplicationOpensearchEmbeddingModelConfigKey            = "opensearch.embedding_model_id"
	ApplicationOpensearchTokenListEmbeddingPathConfigKey    = "opensearch.token_list_embedding_path"

	ApplicationStockSearchRecommendQueryKConfigKey         = "stockSearchRecommendQuery.k"
	ApplicationStockSearchRecommendQuerySizeConfigKey      = "stockSearchRecommendQuery.size"
	ApplicationStockSearchRecommendQueryFuzzinessConfigKey = "stockSearchRecommendQuery.fuzziness"
	ApplicationStockSearchRecommendQueryBoostConfigKey     = "stockSearchRecommendQuery.boost"
	ApplicationStockSearchRecommendQueryExcludeConfigKey   = "stockSearchRecommendQuery.exclude"

	ApplicationStockSearchAboutUsQueryKConfigKey         = "stockSearchAboutUsQuery.k"
	ApplicationStockSearchAboutUsQueryFuzzinessConfigKey = "stockSearchAboutUsQuery.fuzziness"
	ApplicationStockSearchAboutUsQueryFieldsConfigKey    = "stockSearchAboutUsQuery.fields"
	ApplicationStockSearchAboutUsQueryExcludeConfigKey   = "stockSearchAboutUsQuery.exclude"
)
